### ISSUE TITLE
Adding support for Binance Jersy Websocket

### ISSUE THREAD

**Issue by bithon** [unicorn-data-analysis/unicorn-binance-websocket-api#21]
I tested a connection to wss://stream.binance.je:9443/ and it seems to work,...
`{'stream_type': '!ticker@arr', 'event_type': '24hrTicker', 'data': [{'stream_type': '!ticker@arr', 'event_type': '24hrTicker', 'event_time': 1560801108120, 'symbol': 'ETHGBP', 'price_change': '6.04', 'price_change_percent': '2.818', 'weighted_average_price': '219.05', 'trade_before_24h_window': '214.37', 'last_price': '220.41', 'last_quantity': '4.08670000', 'best_bid_price': '217.17', 'best_bid_quantity': '0.50740000', 'best_ask_price': '220.45', 'best_ask_quantity': '0.72840000', 'open_price': '214.37', 'high_price': '225.85', 'low_price': '214.37', 'total_traded_base_asset_volume': '26.77250000', 'total_traded_quote_asset_volume': '5864.60', 'statistics_open_time': 1560714708118, 'statistics_close_time': 1560801108118, 'first_trade_id': 6961, 'last_trade_id': 7004, 'total_nr_of_trades': 44}], 'unicorn_fied': ['binance', '0.1.1']}`

**Comment by bithon** [comment]
Create an instance for Binance Jersy:
`binance_websocket_api_manager = BinanceWebSocketApiManager(exchange="binance.je")`

**Comment by bithon** [comment]
![binance_jersey_websocket_api_python](https://user-images.githubusercontent.com/47597331/59670430-39233a80-91bc-11e9-9ed3-907dbc5f2024.png)

**Comment by DaWe35** [comment]
Wow good job :)
