### ISSUE TITLE
Stream returns string instead of json

### ISSUE THREAD

**Issue by eylence** [unicorn-data-analysis/unicorn-binance-websocket-api#24]
Hi,

the miniTicker stream returns strings instead of dictionary 

```
    def process_stream_data(msg):
        print(type(msg))
    def new_stream():
        binance_websocket_api_manager = BinanceWebSocketApiManager(process_stream_data)
        markets = {'btcusdt'}
        channels = {'miniTicker'}
        binance_websocket_api_manager.create_stream(channels, markets)

    new_stream()
```

output:

```
<class 'str'>
<class 'str'>
....
```

unicorn-binance-websocket-api version 1.4.0

**Comment by bithon** [comment]
Hello!
This is what happens on receive: https://github.com/unicorn-data-analysis/unicorn-binance-websocket-api/blob/master/unicorn_binance_websocket_api/unicorn_binance_websocket_api_socket.py#L62

I havent tested or researched anything now, but i would believe json received through a websocket is string type in the first place.

If you need help on miniTicker please take a look to this example:
https://github.com/unicorn-data-analysis/unicorn-binance-websocket-api/blob/master/example_ticker_and_miniticker.py
which is using this class for processing:
https://github.com/unicorn-data-analysis/unicorn-binance-websocket-api/blob/master/unicorn_binance_websocket_api_process_streams.py 

Best regards!

**Comment by bithon** [comment]
This class can help you, to manage your receives with less effort:
https://github.com/unicorn-data-analysis/unicorn_fy

**Comment by bithon** [comment]
eylence: Please feel free to reopen if you have further questions on this topic!
