### ISSUE TITLE
Sleep in your code might slow things down

### ISSUE THREAD

**Issue by tvdsluijs** [unicorn-data-analysis/unicorn-binance-websocket-api#30]
Your code works really well, thank you but I've got the feeling it's not realtime!
I've looked into your code and found some time.sleep statements.

And it looks like it waits until giving the data to me.

If this is a websocket why are there sleep times build in to it?

Thank you

**Comment by bithon** [comment]
hi!
this is the code for receiving new messages, its running in an endless loop ... https://github.com/unicorn-data-analysis/unicorn-binance-websocket-api/blob/d48ede260ed0f056feb9b30c889263a122854093/unicorn_binance_websocket_api/unicorn_binance_websocket_api_socket.py#L62

there are some time.sleeps for exception handling and reconnects, its not good to bomb the binance server on errors. there are also routines to check the heart beats, restart streams, ...

a short answer: receiving new messages is real time.
